apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-kafka-producer
  template:
    metadata:
      labels:
        app: spring-boot-kafka-producer
    spec:
      containers:
        - name: spring-boot-kafka-producer
          image: rolandojavier13/spring-boot-kafka-producer:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "256m"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-kafka-producer
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-boot-kafka-producer
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spirng-boot-kafka-producer
  annotations:
#    nginx.ingress.kubernetes.io/use-regex: "true"
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /events
            pathType: Prefix
            backend:
              service:
                name: spring-boot-kafka-producer
                port:
                  number: 8080