
topic:
  name: java-topic


spring:
  application:
    name: spring-boot-kafka-producer
  kafka:
    producer:
      bootstrap-servers: "127.0.0.1:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
